(part "SiT9120AI-2D3-33E100_000000"
    (packageRef "QFN_7050_6pins")
    (interface
        (port "1" (symbPinId 1) (portName "NC/OE/%ST%") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "OUT+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT-") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "SiTime")
    (property "Manufacturer_Part_Number" "SiT9120AI-2D3-33E100.000000")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Standard Frequency Differential Oscillator, 7 x 5mm, 6-Pin Package")
    (property "Datasheet_Link" "https://www.sitime.com/support/resource-library/datasheets/sit9120-datasheet")
    (property "symbolName1" "SiT9120AI-2D3-33E100_000000")
)
